/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OrganizationUserInviteDataOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationUserInviteDataOrganization{}

// OrganizationUserInviteDataOrganization struct for OrganizationUserInviteDataOrganization
type OrganizationUserInviteDataOrganization struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type _OrganizationUserInviteDataOrganization OrganizationUserInviteDataOrganization

// NewOrganizationUserInviteDataOrganization instantiates a new OrganizationUserInviteDataOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUserInviteDataOrganization(id string, name string) *OrganizationUserInviteDataOrganization {
	this := OrganizationUserInviteDataOrganization{}
	this.Id = id
	this.Name = name
	return &this
}

// NewOrganizationUserInviteDataOrganizationWithDefaults instantiates a new OrganizationUserInviteDataOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUserInviteDataOrganizationWithDefaults() *OrganizationUserInviteDataOrganization {
	this := OrganizationUserInviteDataOrganization{}
	return &this
}

// GetId returns the Id field value
func (o *OrganizationUserInviteDataOrganization) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrganizationUserInviteDataOrganization) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrganizationUserInviteDataOrganization) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *OrganizationUserInviteDataOrganization) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationUserInviteDataOrganization) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationUserInviteDataOrganization) SetName(v string) {
	o.Name = v
}

func (o OrganizationUserInviteDataOrganization) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationUserInviteDataOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *OrganizationUserInviteDataOrganization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationUserInviteDataOrganization := _OrganizationUserInviteDataOrganization{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationUserInviteDataOrganization)

	if err != nil {
		return err
	}

	*o = OrganizationUserInviteDataOrganization(varOrganizationUserInviteDataOrganization)

	return err
}

type NullableOrganizationUserInviteDataOrganization struct {
	value *OrganizationUserInviteDataOrganization
	isSet bool
}

func (v NullableOrganizationUserInviteDataOrganization) Get() *OrganizationUserInviteDataOrganization {
	return v.value
}

func (v *NullableOrganizationUserInviteDataOrganization) Set(val *OrganizationUserInviteDataOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUserInviteDataOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUserInviteDataOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUserInviteDataOrganization(val *OrganizationUserInviteDataOrganization) *NullableOrganizationUserInviteDataOrganization {
	return &NullableOrganizationUserInviteDataOrganization{value: val, isSet: true}
}

func (v NullableOrganizationUserInviteDataOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUserInviteDataOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
