/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CommitAuthorDraft type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitAuthorDraft{}

// CommitAuthorDraft struct for CommitAuthorDraft
type CommitAuthorDraft struct {
	Name                 string    `json:"name"`
	Email                string    `json:"email"`
	Date                 time.Time `json:"date"`
	AdditionalProperties map[string]interface{}
}

type _CommitAuthorDraft CommitAuthorDraft

// NewCommitAuthorDraft instantiates a new CommitAuthorDraft object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitAuthorDraft(name string, email string, date time.Time) *CommitAuthorDraft {
	this := CommitAuthorDraft{}
	this.Name = name
	this.Email = email
	this.Date = date
	return &this
}

// NewCommitAuthorDraftWithDefaults instantiates a new CommitAuthorDraft object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitAuthorDraftWithDefaults() *CommitAuthorDraft {
	this := CommitAuthorDraft{}
	return &this
}

// GetName returns the Name field value
func (o *CommitAuthorDraft) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CommitAuthorDraft) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CommitAuthorDraft) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CommitAuthorDraft) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CommitAuthorDraft) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CommitAuthorDraft) SetEmail(v string) {
	o.Email = v
}

// GetDate returns the Date field value
func (o *CommitAuthorDraft) GetDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *CommitAuthorDraft) GetDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *CommitAuthorDraft) SetDate(v time.Time) {
	o.Date = v
}

func (o CommitAuthorDraft) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitAuthorDraft) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	toSerialize["date"] = o.Date

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommitAuthorDraft) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
		"date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommitAuthorDraft := _CommitAuthorDraft{}

	err = json.Unmarshal(data, &varCommitAuthorDraft)

	if err != nil {
		return err
	}

	*o = CommitAuthorDraft(varCommitAuthorDraft)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "email")
		delete(additionalProperties, "date")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommitAuthorDraft struct {
	value *CommitAuthorDraft
	isSet bool
}

func (v NullableCommitAuthorDraft) Get() *CommitAuthorDraft {
	return v.value
}

func (v *NullableCommitAuthorDraft) Set(val *CommitAuthorDraft) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitAuthorDraft) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitAuthorDraft) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitAuthorDraft(val *CommitAuthorDraft) *NullableCommitAuthorDraft {
	return &NullableCommitAuthorDraft{value: val, isSet: true}
}

func (v NullableCommitAuthorDraft) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitAuthorDraft) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
