/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ComponentVersionCommits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentVersionCommits{}

// ComponentVersionCommits struct for ComponentVersionCommits
type ComponentVersionCommits struct {
	Commits []CommitData `json:"commits"`
}

type _ComponentVersionCommits ComponentVersionCommits

// NewComponentVersionCommits instantiates a new ComponentVersionCommits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentVersionCommits(commits []CommitData) *ComponentVersionCommits {
	this := ComponentVersionCommits{}
	this.Commits = commits
	return &this
}

// NewComponentVersionCommitsWithDefaults instantiates a new ComponentVersionCommits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentVersionCommitsWithDefaults() *ComponentVersionCommits {
	this := ComponentVersionCommits{}
	return &this
}

// GetCommits returns the Commits field value
func (o *ComponentVersionCommits) GetCommits() []CommitData {
	if o == nil {
		var ret []CommitData
		return ret
	}

	return o.Commits
}

// GetCommitsOk returns a tuple with the Commits field value
// and a boolean to check if the value has been set.
func (o *ComponentVersionCommits) GetCommitsOk() ([]CommitData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Commits, true
}

// SetCommits sets field value
func (o *ComponentVersionCommits) SetCommits(v []CommitData) {
	o.Commits = v
}

func (o ComponentVersionCommits) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentVersionCommits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commits"] = o.Commits
	return toSerialize, nil
}

func (o *ComponentVersionCommits) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"commits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComponentVersionCommits := _ComponentVersionCommits{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComponentVersionCommits)

	if err != nil {
		return err
	}

	*o = ComponentVersionCommits(varComponentVersionCommits)

	return err
}

type NullableComponentVersionCommits struct {
	value *ComponentVersionCommits
	isSet bool
}

func (v NullableComponentVersionCommits) Get() *ComponentVersionCommits {
	return v.value
}

func (v *NullableComponentVersionCommits) Set(val *ComponentVersionCommits) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentVersionCommits) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentVersionCommits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentVersionCommits(val *ComponentVersionCommits) *NullableComponentVersionCommits {
	return &NullableComponentVersionCommits{value: val, isSet: true}
}

func (v NullableComponentVersionCommits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentVersionCommits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
