/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
)

// ApiClientPaginatorAllOf struct for ApiClientPaginatorAllOf
type ApiClientPaginatorAllOf struct {
	Results []ApiClient `json:"results,omitempty"`
}

// NewApiClientPaginatorAllOf instantiates a new ApiClientPaginatorAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClientPaginatorAllOf() *ApiClientPaginatorAllOf {
	this := ApiClientPaginatorAllOf{}
	return &this
}

// NewApiClientPaginatorAllOfWithDefaults instantiates a new ApiClientPaginatorAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClientPaginatorAllOfWithDefaults() *ApiClientPaginatorAllOf {
	this := ApiClientPaginatorAllOf{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ApiClientPaginatorAllOf) GetResults() []ApiClient {
	if o == nil || o.Results == nil {
		var ret []ApiClient
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClientPaginatorAllOf) GetResultsOk() ([]ApiClient, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ApiClientPaginatorAllOf) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []ApiClient and assigns it to the Results field.
func (o *ApiClientPaginatorAllOf) SetResults(v []ApiClient) {
	o.Results = v
}

func (o ApiClientPaginatorAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableApiClientPaginatorAllOf struct {
	value *ApiClientPaginatorAllOf
	isSet bool
}

func (v NullableApiClientPaginatorAllOf) Get() *ApiClientPaginatorAllOf {
	return v.value
}

func (v *NullableApiClientPaginatorAllOf) Set(val *ApiClientPaginatorAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClientPaginatorAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClientPaginatorAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClientPaginatorAllOf(val *ApiClientPaginatorAllOf) *NullableApiClientPaginatorAllOf {
	return &NullableApiClientPaginatorAllOf{value: val, isSet: true}
}

func (v NullableApiClientPaginatorAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClientPaginatorAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
