/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.   All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
)

// OrganizationUserInvite struct for OrganizationUserInvite
type OrganizationUserInvite struct {
	// E-mail address of the user
	Email string `json:"email"`
}

// NewOrganizationUserInvite instantiates a new OrganizationUserInvite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUserInvite(email string) *OrganizationUserInvite {
	this := OrganizationUserInvite{}
	this.Email = email
	return &this
}

// NewOrganizationUserInviteWithDefaults instantiates a new OrganizationUserInvite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUserInviteWithDefaults() *OrganizationUserInvite {
	this := OrganizationUserInvite{}
	return &this
}

// GetEmail returns the Email field value
func (o *OrganizationUserInvite) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *OrganizationUserInvite) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *OrganizationUserInvite) SetEmail(v string) {
	o.Email = v
}

func (o OrganizationUserInvite) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationUserInvite struct {
	value *OrganizationUserInvite
	isSet bool
}

func (v NullableOrganizationUserInvite) Get() *OrganizationUserInvite {
	return v.value
}

func (v *NullableOrganizationUserInvite) Set(val *OrganizationUserInvite) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUserInvite) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUserInvite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUserInvite(val *OrganizationUserInvite) *NullableOrganizationUserInvite {
	return &NullableOrganizationUserInvite{value: val, isSet: true}
}

func (v NullableOrganizationUserInvite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUserInvite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
