/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.   All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
)

// OrganizationUserProjectsInner struct for OrganizationUserProjectsInner
type OrganizationUserProjectsInner struct {
	Name   *string  `json:"name,omitempty"`
	Key    *string  `json:"key,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
}

// NewOrganizationUserProjectsInner instantiates a new OrganizationUserProjectsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUserProjectsInner() *OrganizationUserProjectsInner {
	this := OrganizationUserProjectsInner{}
	return &this
}

// NewOrganizationUserProjectsInnerWithDefaults instantiates a new OrganizationUserProjectsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUserProjectsInnerWithDefaults() *OrganizationUserProjectsInner {
	this := OrganizationUserProjectsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrganizationUserProjectsInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationUserProjectsInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrganizationUserProjectsInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrganizationUserProjectsInner) SetName(v string) {
	o.Name = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *OrganizationUserProjectsInner) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationUserProjectsInner) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *OrganizationUserProjectsInner) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *OrganizationUserProjectsInner) SetKey(v string) {
	o.Key = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *OrganizationUserProjectsInner) GetScopes() []string {
	if o == nil || o.Scopes == nil {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationUserProjectsInner) GetScopesOk() ([]string, bool) {
	if o == nil || o.Scopes == nil {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *OrganizationUserProjectsInner) HasScopes() bool {
	if o != nil && o.Scopes != nil {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *OrganizationUserProjectsInner) SetScopes(v []string) {
	o.Scopes = v
}

func (o OrganizationUserProjectsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Scopes != nil {
		toSerialize["scopes"] = o.Scopes
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationUserProjectsInner struct {
	value *OrganizationUserProjectsInner
	isSet bool
}

func (v NullableOrganizationUserProjectsInner) Get() *OrganizationUserProjectsInner {
	return v.value
}

func (v *NullableOrganizationUserProjectsInner) Set(val *OrganizationUserProjectsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUserProjectsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUserProjectsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUserProjectsInner(val *OrganizationUserProjectsInner) *NullableOrganizationUserProjectsInner {
	return &NullableOrganizationUserProjectsInner{value: val, isSet: true}
}

func (v NullableOrganizationUserProjectsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUserProjectsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
