/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.   All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
)

// CommitDataPaginatorAllOf struct for CommitDataPaginatorAllOf
type CommitDataPaginatorAllOf struct {
	Results []CommitData `json:"results,omitempty"`
}

// NewCommitDataPaginatorAllOf instantiates a new CommitDataPaginatorAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitDataPaginatorAllOf() *CommitDataPaginatorAllOf {
	this := CommitDataPaginatorAllOf{}
	return &this
}

// NewCommitDataPaginatorAllOfWithDefaults instantiates a new CommitDataPaginatorAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitDataPaginatorAllOfWithDefaults() *CommitDataPaginatorAllOf {
	this := CommitDataPaginatorAllOf{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CommitDataPaginatorAllOf) GetResults() []CommitData {
	if o == nil || o.Results == nil {
		var ret []CommitData
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitDataPaginatorAllOf) GetResultsOk() ([]CommitData, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CommitDataPaginatorAllOf) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []CommitData and assigns it to the Results field.
func (o *CommitDataPaginatorAllOf) SetResults(v []CommitData) {
	o.Results = v
}

func (o CommitDataPaginatorAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableCommitDataPaginatorAllOf struct {
	value *CommitDataPaginatorAllOf
	isSet bool
}

func (v NullableCommitDataPaginatorAllOf) Get() *CommitDataPaginatorAllOf {
	return v.value
}

func (v *NullableCommitDataPaginatorAllOf) Set(val *CommitDataPaginatorAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitDataPaginatorAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitDataPaginatorAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitDataPaginatorAllOf(val *CommitDataPaginatorAllOf) *NullableCommitDataPaginatorAllOf {
	return &NullableCommitDataPaginatorAllOf{value: val, isSet: true}
}

func (v NullableCommitDataPaginatorAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitDataPaginatorAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
