/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
)

// JSONPatchRequestMoveCopy struct for JSONPatchRequestMoveCopy
type JSONPatchRequestMoveCopy struct {
	// A JSON Pointer path.
	Path string `json:"path"`
	// The operation to perform.
	Op string `json:"op"`
}

// NewJSONPatchRequestMoveCopy instantiates a new JSONPatchRequestMoveCopy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJSONPatchRequestMoveCopy(path string, op string) *JSONPatchRequestMoveCopy {
	this := JSONPatchRequestMoveCopy{}
	this.Path = path
	this.Op = op
	return &this
}

// NewJSONPatchRequestMoveCopyWithDefaults instantiates a new JSONPatchRequestMoveCopy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJSONPatchRequestMoveCopyWithDefaults() *JSONPatchRequestMoveCopy {
	this := JSONPatchRequestMoveCopy{}
	return &this
}

// GetPath returns the Path field value
func (o *JSONPatchRequestMoveCopy) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *JSONPatchRequestMoveCopy) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *JSONPatchRequestMoveCopy) SetPath(v string) {
	o.Path = v
}

// GetOp returns the Op field value
func (o *JSONPatchRequestMoveCopy) GetOp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *JSONPatchRequestMoveCopy) GetOpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *JSONPatchRequestMoveCopy) SetOp(v string) {
	o.Op = v
}

func (o JSONPatchRequestMoveCopy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["path"] = o.Path
	}
	if true {
		toSerialize["op"] = o.Op
	}
	return json.Marshal(toSerialize)
}

type NullableJSONPatchRequestMoveCopy struct {
	value *JSONPatchRequestMoveCopy
	isSet bool
}

func (v NullableJSONPatchRequestMoveCopy) Get() *JSONPatchRequestMoveCopy {
	return v.value
}

func (v *NullableJSONPatchRequestMoveCopy) Set(val *JSONPatchRequestMoveCopy) {
	v.value = val
	v.isSet = true
}

func (v NullableJSONPatchRequestMoveCopy) IsSet() bool {
	return v.isSet
}

func (v *NullableJSONPatchRequestMoveCopy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJSONPatchRequestMoveCopy(val *JSONPatchRequestMoveCopy) *NullableJSONPatchRequestMoveCopy {
	return &NullableJSONPatchRequestMoveCopy{value: val, isSet: true}
}

func (v NullableJSONPatchRequestMoveCopy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJSONPatchRequestMoveCopy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
