/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the OrganizationUserInvite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationUserInvite{}

// OrganizationUserInvite struct for OrganizationUserInvite
type OrganizationUserInvite struct {
	CreatedBy *string `json:"created_by,omitempty"`
	// E-mail address of the user
	Email string `json:"email"`
	// Key of the project to invite user to
	ProjectKey *string `json:"project_key,omitempty"`
	// Role for the user
	Role *string `json:"role,omitempty"`
}

type _OrganizationUserInvite OrganizationUserInvite

// NewOrganizationUserInvite instantiates a new OrganizationUserInvite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUserInvite(email string) *OrganizationUserInvite {
	this := OrganizationUserInvite{}
	this.Email = email
	return &this
}

// NewOrganizationUserInviteWithDefaults instantiates a new OrganizationUserInvite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUserInviteWithDefaults() *OrganizationUserInvite {
	this := OrganizationUserInvite{}
	return &this
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *OrganizationUserInvite) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationUserInvite) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *OrganizationUserInvite) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *OrganizationUserInvite) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetEmail returns the Email field value
func (o *OrganizationUserInvite) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *OrganizationUserInvite) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *OrganizationUserInvite) SetEmail(v string) {
	o.Email = v
}

// GetProjectKey returns the ProjectKey field value if set, zero value otherwise.
func (o *OrganizationUserInvite) GetProjectKey() string {
	if o == nil || IsNil(o.ProjectKey) {
		var ret string
		return ret
	}
	return *o.ProjectKey
}

// GetProjectKeyOk returns a tuple with the ProjectKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationUserInvite) GetProjectKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectKey) {
		return nil, false
	}
	return o.ProjectKey, true
}

// HasProjectKey returns a boolean if a field has been set.
func (o *OrganizationUserInvite) HasProjectKey() bool {
	if o != nil && !IsNil(o.ProjectKey) {
		return true
	}

	return false
}

// SetProjectKey gets a reference to the given string and assigns it to the ProjectKey field.
func (o *OrganizationUserInvite) SetProjectKey(v string) {
	o.ProjectKey = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *OrganizationUserInvite) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationUserInvite) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *OrganizationUserInvite) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *OrganizationUserInvite) SetRole(v string) {
	o.Role = &v
}

func (o OrganizationUserInvite) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationUserInvite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	toSerialize["email"] = o.Email
	if !IsNil(o.ProjectKey) {
		toSerialize["project_key"] = o.ProjectKey
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *OrganizationUserInvite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationUserInvite := _OrganizationUserInvite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationUserInvite)

	if err != nil {
		return err
	}

	*o = OrganizationUserInvite(varOrganizationUserInvite)

	return err
}

type NullableOrganizationUserInvite struct {
	value *OrganizationUserInvite
	isSet bool
}

func (v NullableOrganizationUserInvite) Get() *OrganizationUserInvite {
	return v.value
}

func (v *NullableOrganizationUserInvite) Set(val *OrganizationUserInvite) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUserInvite) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUserInvite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUserInvite(val *OrganizationUserInvite) *NullableOrganizationUserInvite {
	return &NullableOrganizationUserInvite{value: val, isSet: true}
}

func (v NullableOrganizationUserInvite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUserInvite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
