/*
MACH composer Cloud (MCC) Public API

# Introduction  MACH composer Cloud is a platform and API to facilitate and coordinate work across teams that build composable architectures using MACH technology.  All operations available in MACH composer cloud are available through this API. For more information about using it in your MACH architecture, have a look at the [documentation website](https://docs.machcomposer.io/cloud/index.html).

API version: 0.1.0
Contact: mach@labdigital.nl
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mccsdk

import (
	"encoding/json"
	"time"
)

// checks if the PatchedApiClientDraft type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedApiClientDraft{}

// PatchedApiClientDraft struct for PatchedApiClientDraft
type PatchedApiClientDraft struct {
	Name     *string `json:"name,omitempty"`
	ClientId *string `json:"client_id,omitempty"`
	// Hashed on Save. Copy it now if this is a new secret.
	ClientSecret         *string      `json:"client_secret,omitempty"`
	Scope                []string     `json:"scope,omitempty"`
	Description          *string      `json:"description,omitempty"`
	LastUsedAt           NullableTime `json:"last_used_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedApiClientDraft PatchedApiClientDraft

// NewPatchedApiClientDraft instantiates a new PatchedApiClientDraft object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedApiClientDraft() *PatchedApiClientDraft {
	this := PatchedApiClientDraft{}
	return &this
}

// NewPatchedApiClientDraftWithDefaults instantiates a new PatchedApiClientDraft object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedApiClientDraftWithDefaults() *PatchedApiClientDraft {
	this := PatchedApiClientDraft{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedApiClientDraft) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedApiClientDraft) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedApiClientDraft) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedApiClientDraft) SetName(v string) {
	o.Name = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *PatchedApiClientDraft) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedApiClientDraft) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *PatchedApiClientDraft) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *PatchedApiClientDraft) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *PatchedApiClientDraft) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedApiClientDraft) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *PatchedApiClientDraft) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *PatchedApiClientDraft) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *PatchedApiClientDraft) GetScope() []string {
	if o == nil || IsNil(o.Scope) {
		var ret []string
		return ret
	}
	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedApiClientDraft) GetScopeOk() ([]string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *PatchedApiClientDraft) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given []string and assigns it to the Scope field.
func (o *PatchedApiClientDraft) SetScope(v []string) {
	o.Scope = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedApiClientDraft) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedApiClientDraft) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedApiClientDraft) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedApiClientDraft) SetDescription(v string) {
	o.Description = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedApiClientDraft) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedApiClientDraft) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *PatchedApiClientDraft) HasLastUsedAt() bool {
	if o != nil && o.LastUsedAt.IsSet() {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given NullableTime and assigns it to the LastUsedAt field.
func (o *PatchedApiClientDraft) SetLastUsedAt(v time.Time) {
	o.LastUsedAt.Set(&v)
}

// SetLastUsedAtNil sets the value for LastUsedAt to be an explicit nil
func (o *PatchedApiClientDraft) SetLastUsedAtNil() {
	o.LastUsedAt.Set(nil)
}

// UnsetLastUsedAt ensures that no value is present for LastUsedAt, not even an explicit nil
func (o *PatchedApiClientDraft) UnsetLastUsedAt() {
	o.LastUsedAt.Unset()
}

func (o PatchedApiClientDraft) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedApiClientDraft) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ClientId) {
		toSerialize["client_id"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["client_secret"] = o.ClientSecret
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.LastUsedAt.IsSet() {
		toSerialize["last_used_at"] = o.LastUsedAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedApiClientDraft) UnmarshalJSON(data []byte) (err error) {
	varPatchedApiClientDraft := _PatchedApiClientDraft{}

	err = json.Unmarshal(data, &varPatchedApiClientDraft)

	if err != nil {
		return err
	}

	*o = PatchedApiClientDraft(varPatchedApiClientDraft)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "client_id")
		delete(additionalProperties, "client_secret")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "description")
		delete(additionalProperties, "last_used_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedApiClientDraft struct {
	value *PatchedApiClientDraft
	isSet bool
}

func (v NullablePatchedApiClientDraft) Get() *PatchedApiClientDraft {
	return v.value
}

func (v *NullablePatchedApiClientDraft) Set(val *PatchedApiClientDraft) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedApiClientDraft) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedApiClientDraft) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedApiClientDraft(val *PatchedApiClientDraft) *NullablePatchedApiClientDraft {
	return &NullablePatchedApiClientDraft{value: val, isSet: true}
}

func (v NullablePatchedApiClientDraft) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedApiClientDraft) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
