version: '3'

tasks:
  test:
      cmds:
        - go test ./...

  clean:
    cmds:
      - rm -f *.go
      - rm -rf docs
      - rm -rf api
      - rm -rf tmp

  generate:
    cmds:
      - rm -rf mccsdk docs
      - openapi-generator-cli generate -i https://api.mach.cloud/docs/openapi.yaml -g go --enable-post-process-file -c ./openapi-config.yaml
      - mkdir mccsdk
      - mv *.go mccsdk
      - rm -rf test
      - go fmt ./...
      - go mod tidy
