name: Generate release pull request

on:
  push:
    branches: [ "main" ]

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@8501c67fb51f2e1dbde2f4768f484e1534a26819 # v0.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
