name: Run tests

on: [ pull_request ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: golangci-lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@v6
      with:
        args: --issues-exit-code=0 --timeout=5m

    - name: Run tests
      run: go test -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... -v ./...

    - name: Upload to codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true

