name: Run tests

on: [ pull_request ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version-file: go.mod

    - name: golangci-lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6.5.2
      with:
        args: --issues-exit-code=0 --timeout=5m

    - name: Run tests
      run: go test -race -coverprofile=coverage.out -covermode=atomic -coverpkg=./... -v ./...

    - name: Upload to codecov
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      with:
        verbose: true

